version: '3'

services:

  nba-salaries-app:
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - LOCAL=true
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
    volumes:
      - "./:/var/www/html/"

  mysql-db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - "./localdb:/var/lib/mysql"

  nba-salaries-app-phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: unless-stopped
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql-db
        - PMA_USER=root
        - PMA_PASSWORD=my-secret-pw
      ports:
        - 8081:80
      links:
        - mysql-db:db
